'use client';

import React from 'react';
import Link from 'next/link';
import { Award, Search, Filter } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';

const API_BASE = 'http://localhost:9758/api';

type Certificate = {
  id: string;
  device_id: string;
  device_model?: string;
  device_technology?: string;
  assurance_status: string;
  lifecycle_decision: string;
  generated_at: string;
};

const STATUS_OPTIONS = [
  { value: 'ALL', label: 'All Statuses' },
  { value: 'SANITIZED_REUSABLE', label: 'Sanitized & Reusable' },
  { value: 'SANITIZATION_NOT_VERIFIABLE', label: 'Not Verifiable' },
  { value: 'SANITIZATION_FAILED', label: 'Sanitization Failed' },
  { value: 'DISPOSAL_REQUIRED', label: 'Disposal Required' },
];

function getAssuranceBadge(status: string) {
  switch (status) {
    case 'SANITIZED_REUSABLE':
      return (
        <Badge className="bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200 border-green-300">
          ✅ Sanitized & Reusable
        </Badge>
      );
    case 'SANITIZATION_NOT_VERIFIABLE':
      return (
        <Badge className="bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200 border-yellow-300">
          ⚠️ Not Verifiable
        </Badge>
      );
    case 'SANITIZATION_FAILED':
      return (
        <Badge className="bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200 border-red-300">
          ❌ Failed
        </Badge>
      );
    case 'DISPOSAL_REQUIRED':
      return (
        <Badge className="bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200 border-orange-300">
          🗑️ Disposal Required
        </Badge>
      );
    default:
      return <Badge variant="outline">{status}</Badge>;
  }
}

function getDecisionBadge(decision: string) {
  switch (decision) {
    case 'REUSE':
      return <Badge className="bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200">Reuse</Badge>;
    case 'REVIEW':
      return <Badge className="bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200">Review</Badge>;
    case 'DISPOSAL_REQUIRED':
      return <Badge className="bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200">Disposal</Badge>;
    default:
      return <Badge variant="outline">{decision || '—'}</Badge>;
  }
}

const PAGE_SIZE = 20;

export default function CertificatesPage() {
  const [certificates, setCertificates] = React.useState<Certificate[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);
  const [search, setSearch] = React.useState('');
  const [statusFilter, setStatusFilter] = React.useState('ALL');
  const [page, setPage] = React.useState(1);

  React.useEffect(() => {
    async function fetchCerts() {
      setLoading(true);
      setError(null);
      try {
        const res = await fetch(`${API_BASE}/compliance/certificates`);
        if (!res.ok) throw new Error(`Server returned ${res.status}`);
        const data = await res.json();
        setCertificates(Array.isArray(data) ? data : (data.certificates ?? []));
      } catch (err: any) {
        setError(err.message ?? 'Failed to load certificates.');
        setCertificates([]);
      } finally {
        setLoading(false);
      }
    }
    fetchCerts();
  }, []);

  const filtered = certificates.filter((c) => {
    const matchStatus = statusFilter === 'ALL' || c.assurance_status === statusFilter;
    const term = search.toLowerCase();
    const matchSearch =
      !term ||
      c.id.toLowerCase().includes(term) ||
      (c.device_model ?? '').toLowerCase().includes(term) ||
      c.device_id.toLowerCase().includes(term);
    return matchStatus && matchSearch;
  });

  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const paginated = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-center gap-3">
        <Award className="h-7 w-7 text-primary" />
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Sanitization Certificates</h1>
          <p className="text-muted-foreground">
            All device sanitization certificates generated by SecureWipe.
          </p>
        </div>
      </div>

      <Card>
        <CardHeader>
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3">
            <CardTitle className="text-base">All Certificates</CardTitle>
            <div className="flex items-center gap-2 ml-auto w-full sm:w-auto">
              <div className="relative flex-1 sm:flex-none">
                <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search by ID or device…"
                  className="pl-8 sm:w-[260px]"
                  value={search}
                  onChange={(e) => { setSearch(e.target.value); setPage(1); }}
                />
              </div>
              <Select value={statusFilter} onValueChange={(v) => { setStatusFilter(v); setPage(1); }}>
                <SelectTrigger className="w-[190px]">
                  <Filter className="h-4 w-4 mr-1.5" />
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {STATUS_OPTIONS.map((o) => (
                    <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <CardDescription>
            {loading ? 'Loading…' : `${filtered.length} certificate${filtered.length !== 1 ? 's' : ''} found`}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Certificate ID</TableHead>
                <TableHead>Device</TableHead>
                <TableHead>Technology</TableHead>
                <TableHead>Assurance Status</TableHead>
                <TableHead>Decision</TableHead>
                <TableHead>Generated At</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading ? (
                <TableRow>
                  <TableCell colSpan={7} className="text-center py-10 text-muted-foreground">
                    Loading certificates…
                  </TableCell>
                </TableRow>
              ) : error ? (
                <TableRow>
                  <TableCell colSpan={7} className="text-center py-10 text-red-500">
                    {error}
                  </TableCell>
                </TableRow>
              ) : paginated.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={7} className="text-center py-10 text-muted-foreground">
                    {search || statusFilter !== 'ALL'
                      ? 'No certificates match your filters.'
                      : 'No certificates yet. Run a sanitization workflow to generate the first certificate.'}
                  </TableCell>
                </TableRow>
              ) : (
                paginated.map((cert) => (
                  <TableRow key={cert.id}>
                    <TableCell className="font-mono text-xs font-semibold">
                      {cert.id.substring(0, 18)}…
                    </TableCell>
                    <TableCell>
                      <div className="font-medium text-sm">{cert.device_model ?? '—'}</div>
                      <div className="text-[11px] text-muted-foreground font-mono">
                        {cert.device_id.substring(0, 16)}…
                      </div>
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground">
                      {cert.device_technology ?? '—'}
                    </TableCell>
                    <TableCell>{getAssuranceBadge(cert.assurance_status)}</TableCell>
                    <TableCell>{getDecisionBadge(cert.lifecycle_decision)}</TableCell>
                    <TableCell className="text-xs text-muted-foreground">
                      {cert.generated_at ? new Date(cert.generated_at).toLocaleString() : '—'}
                    </TableCell>
                    <TableCell className="text-right">
                      <Button variant="outline" size="sm" asChild>
                        <Link href={`/lifecycle/certificate/${cert.id}`}>View</Link>
                      </Button>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>

          {!loading && totalPages > 1 && (
            <div className="flex items-center justify-between mt-4 pt-4 border-t">
              <p className="text-sm text-muted-foreground">
                Page {page} of {totalPages}
              </p>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setPage((p) => Math.max(1, p - 1))}
                  disabled={page === 1}
                >
                  Previous
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                  disabled={page === totalPages}
                >
                  Next
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
